import type { ProblemTemplate } from '../types';

export const ADDITION_TEMPLATES: readonly ProblemTemplate[] = [
  {
    id: 'add_single_digit_no_carry',
    operation: 'addition',
    skillId: 'addition.single-digit.no-carry',
    standards: ['1.OA.C.6'],
    grades: [1],
    operandRanges: [
      { min: 1, max: 9 },
      { min: 1, max: 9 },
    ],
    resultRange: { min: 2, max: 10 },
    requiresCarry: false,
    baseElo: 800,
    digitCount: 1,
  },
  {
    id: 'add_within_20_no_carry',
    operation: 'addition',
    skillId: 'addition.within-20.no-carry',
    standards: ['1.OA.C.6'],
    grades: [1],
    operandRanges: [
      { min: 10, max: 19 },
      { min: 1, max: 9 },
    ],
    resultRange: { min: 11, max: 19 },
    requiresCarry: false,
    baseElo: 850,
    digitCount: 2,
  },
  {
    id: 'add_within_20_with_carry',
    operation: 'addition',
    skillId: 'addition.within-20.with-carry',
    standards: ['1.OA.C.6'],
    grades: [1],
    operandRanges: [
      { min: 2, max: 9 },
      { min: 2, max: 9 },
    ],
    resultRange: { min: 10, max: 18 },
    requiresCarry: true,
    baseElo: 920,
    digitCount: 1,
  },
  {
    id: 'add_two_digit_no_carry',
    operation: 'addition',
    skillId: 'addition.two-digit.no-carry',
    standards: ['2.NBT.B.5'],
    grades: [2, 3],
    operandRanges: [
      { min: 10, max: 99 },
      { min: 10, max: 99 },
    ],
    resultRange: { min: 20, max: 198 },
    requiresCarry: false,
    baseElo: 1000,
    digitCount: 2,
  },
  {
    id: 'add_two_digit_with_carry',
    operation: 'addition',
    skillId: 'addition.two-digit.with-carry',
    standards: ['2.NBT.B.5'],
    grades: [2, 3],
    operandRanges: [
      { min: 10, max: 99 },
      { min: 10, max: 99 },
    ],
    resultRange: { min: 20, max: 198 },
    requiresCarry: true,
    baseElo: 1080,
    digitCount: 2,
  },
  {
    id: 'add_three_digit_no_carry',
    operation: 'addition',
    skillId: 'addition.three-digit.no-carry',
    standards: ['3.NBT.A.2'],
    grades: [3],
    operandRanges: [
      { min: 100, max: 999 },
      { min: 100, max: 999 },
    ],
    resultRange: { min: 200, max: 1998 },
    requiresCarry: false,
    baseElo: 1150,
    digitCount: 3,
  },
  {
    id: 'add_three_digit_with_carry',
    operation: 'addition',
    skillId: 'addition.three-digit.with-carry',
    standards: ['3.NBT.A.2'],
    grades: [3],
    operandRanges: [
      { min: 100, max: 999 },
      { min: 100, max: 999 },
    ],
    resultRange: { min: 200, max: 1998 },
    requiresCarry: true,
    baseElo: 1250,
    digitCount: 3,
  },
  {
    id: 'add_four_digit_no_carry',
    operation: 'addition',
    skillId: 'addition.four-digit.no-carry',
    standards: ['4.NBT.B.4'],
    grades: [4],
    operandRanges: [
      { min: 1000, max: 9999 },
      { min: 1000, max: 9999 },
    ],
    resultRange: { min: 2000, max: 19998 },
    requiresCarry: false,
    baseElo: 1350,
    digitCount: 4,
  },
  {
    id: 'add_four_digit_with_carry',
    operation: 'addition',
    skillId: 'addition.four-digit.with-carry',
    standards: ['4.NBT.B.4'],
    grades: [4],
    operandRanges: [
      { min: 1000, max: 9999 },
      { min: 1000, max: 9999 },
    ],
    resultRange: { min: 2000, max: 19998 },
    requiresCarry: true,
    baseElo: 1450,
    digitCount: 4,
  },
];
