import type { ProblemTemplate } from '../types';

export const COORDINATE_GEOMETRY_TEMPLATES: readonly ProblemTemplate[] = [
  {
    id: 'coord_slope',
    operation: 'coordinate_geometry',
    skillId: 'slope',
    grades: [8, 9],
    baseElo: 1000,
    digitCount: 1,
    distractorStrategy: 'domain_specific',
    standards: ['8.EE.B.5'],
    domainConfig: { type: 'slope' },
  },
  {
    id: 'coord_distance',
    operation: 'coordinate_geometry',
    skillId: 'distance',
    grades: [8, 9],
    baseElo: 1050,
    digitCount: 1,
    distractorStrategy: 'domain_specific',
    standards: ['8.G.B.8'],
    domainConfig: { type: 'distance' },
  },
  {
    id: 'coord_midpoint_x',
    operation: 'coordinate_geometry',
    skillId: 'midpoint',
    grades: [8, 9],
    baseElo: 1050,
    digitCount: 1,
    distractorStrategy: 'domain_specific',
    standards: ['8.G.B.8'],
    domainConfig: { type: 'midpoint_x' },
  },
  {
    id: 'coord_midpoint_y',
    operation: 'coordinate_geometry',
    skillId: 'midpoint',
    grades: [8, 9],
    baseElo: 1050,
    digitCount: 1,
    distractorStrategy: 'domain_specific',
    standards: ['8.G.B.8'],
    domainConfig: { type: 'midpoint_y' },
  },
  {
    id: 'coord_line_yintercept',
    operation: 'coordinate_geometry',
    skillId: 'line_equation_yintercept',
    grades: [9, 10],
    baseElo: 1100,
    digitCount: 1,
    distractorStrategy: 'domain_specific',
    standards: ['8.EE.B.6'],
    domainConfig: { type: 'line_equation_yintercept' },
  },
  {
    id: 'coord_line_slope_from_eq',
    operation: 'coordinate_geometry',
    skillId: 'line_equation_slope',
    grades: [9, 10],
    baseElo: 1200,
    digitCount: 1,
    distractorStrategy: 'domain_specific',
    standards: ['8.EE.B.6'],
    domainConfig: { type: 'line_equation_slope' },
  },
  {
    id: 'coord_word_problem',
    operation: 'coordinate_geometry',
    skillId: 'coord_word_problem',
    grades: [10],
    baseElo: 1200,
    digitCount: 1,
    distractorStrategy: 'domain_specific',
    standards: ['8.EE.B.5', '8.G.B.8'],
    domainConfig: { type: 'distance' },
  },
] as const;
