import type { ProblemTemplate } from '../types';

export const DIVISION_TEMPLATES: readonly ProblemTemplate[] = [
  {
    id: 'div_sharing_equally',
    operation: 'division',
    skillId: 'division.sharing-equally',
    standards: ['3.OA.A.2'],
    grades: [3],
    operandRanges: [
      { min: 4, max: 20 },
      { min: 2, max: 5 },
    ],
    resultRange: { min: 2, max: 10 },
    baseElo: 900,
    digitCount: 1,
  },
  {
    id: 'div_grouping',
    operation: 'division',
    skillId: 'division.grouping',
    standards: ['3.OA.A.2'],
    grades: [3],
    operandRanges: [
      { min: 4, max: 30 },
      { min: 2, max: 6 },
    ],
    resultRange: { min: 2, max: 10 },
    baseElo: 920,
    digitCount: 1,
  },
  {
    id: 'div_facts_within_100',
    operation: 'division',
    skillId: 'division.facts-within-100',
    standards: ['3.OA.C.7'],
    grades: [3],
    operandRanges: [
      { min: 4, max: 81 },
      { min: 2, max: 9 },
    ],
    resultRange: { min: 2, max: 9 },
    baseElo: 1000,
    digitCount: 2,
  },
  {
    id: 'div_relationship_multiplication',
    operation: 'division',
    skillId: 'division.relationship-multiplication',
    standards: ['3.OA.B.6'],
    grades: [3],
    operandRanges: [
      { min: 4, max: 81 },
      { min: 2, max: 9 },
    ],
    resultRange: { min: 2, max: 9 },
    baseElo: 1020,
    digitCount: 2,
  },
  {
    id: 'div_with_remainders',
    operation: 'division',
    skillId: 'division.with-remainders',
    standards: ['4.OA.A.3'],
    grades: [4],
    operandRanges: [
      { min: 10, max: 50 },
      { min: 2, max: 9 },
    ],
    resultRange: { min: 2, max: 25 },
    baseElo: 1050,
    digitCount: 2,
  },
  {
    id: 'div_two_by_one',
    operation: 'division',
    skillId: 'division.two-by-one',
    standards: ['4.NBT.B.6'],
    grades: [4],
    operandRanges: [
      { min: 10, max: 99 },
      { min: 2, max: 9 },
    ],
    resultRange: { min: 2, max: 49 },
    baseElo: 1100,
    digitCount: 2,
  },
  {
    id: 'div_three_by_one',
    operation: 'division',
    skillId: 'division.three-by-one',
    standards: ['4.NBT.B.6'],
    grades: [4],
    operandRanges: [
      { min: 100, max: 999 },
      { min: 2, max: 9 },
    ],
    resultRange: { min: 12, max: 499 },
    baseElo: 1150,
    digitCount: 3,
  },
  {
    id: 'div_multi_step',
    operation: 'division',
    skillId: 'division.multi-step',
    standards: ['4.OA.A.3'],
    grades: [4],
    operandRanges: [
      { min: 20, max: 99 },
      { min: 2, max: 9 },
    ],
    resultRange: { min: 3, max: 49 },
    baseElo: 1200,
    digitCount: 2,
  },
];
