import type { ProblemTemplate } from '../types';

export const EXPONENTS_TEMPLATES: readonly ProblemTemplate[] = [
  {
    id: 'exp_square',
    operation: 'exponents',
    skillId: 'exponents.squares',
    standards: ['5.NBT.A.2'],
    grades: [5],
    baseElo: 950,
    digitCount: 2,
    domainConfig: { type: 'square' },
  },
  {
    id: 'exp_cube',
    operation: 'exponents',
    skillId: 'exponents.cubes',
    standards: ['5.NBT.A.2'],
    grades: [5],
    baseElo: 1000,
    digitCount: 2,
    domainConfig: { type: 'cube' },
  },
  {
    id: 'exp_power_of_10',
    operation: 'exponents',
    skillId: 'exponents.power-of-10',
    standards: ['5.NBT.A.2'],
    grades: [5],
    baseElo: 900,
    digitCount: 3,
    domainConfig: { type: 'power_of_10' },
  },
  {
    id: 'exp_evaluate',
    operation: 'exponents',
    skillId: 'exponents.evaluate',
    standards: ['6.EE.A.1'],
    grades: [6],
    baseElo: 1100,
    digitCount: 2,
    domainConfig: { type: 'evaluate' },
  },
  {
    id: 'exp_square_root',
    operation: 'exponents',
    skillId: 'exponents.square-root',
    standards: ['6.EE.A.1'],
    grades: [6],
    baseElo: 1050,
    digitCount: 2,
    domainConfig: { type: 'square_root' },
  },
];
