import type { ProblemTemplate } from '../types';

export const EXPONENTIAL_FUNCTIONS_TEMPLATES: readonly ProblemTemplate[] = [
  {
    id: 'exp_evaluate_template',
    operation: 'exponential_functions',
    skillId: 'exp_evaluate',
    grades: [9],
    baseElo: 950,
    digitCount: 2,
    distractorStrategy: 'domain_specific',
    standards: ['HSF-LE.A.1'],
    domainConfig: { type: 'exp_evaluate' },
  },
  {
    id: 'exp_growth_factor_template',
    operation: 'exponential_functions',
    skillId: 'growth_factor',
    grades: [10],
    baseElo: 1000,
    digitCount: 2,
    distractorStrategy: 'domain_specific',
    standards: ['HSF-LE.A.1'],
    domainConfig: { type: 'growth_factor' },
  },
  {
    id: 'exp_decay_factor_template',
    operation: 'exponential_functions',
    skillId: 'decay_factor',
    grades: [10],
    baseElo: 1050,
    digitCount: 2,
    distractorStrategy: 'domain_specific',
    standards: ['HSF-LE.A.1'],
    domainConfig: { type: 'decay_factor' },
  },
  {
    id: 'exp_doubling_time_template',
    operation: 'exponential_functions',
    skillId: 'doubling_time',
    grades: [11],
    baseElo: 1100,
    digitCount: 2,
    distractorStrategy: 'domain_specific',
    standards: ['HSF-LE.A.1'],
    domainConfig: { type: 'doubling_time' },
  },
  {
    id: 'exp_word_problem_template',
    operation: 'exponential_functions',
    skillId: 'exp_word_problem',
    grades: [10],
    baseElo: 1150,
    digitCount: 2,
    distractorStrategy: 'domain_specific',
    standards: ['HSF-LE.A.1'],
    domainConfig: { type: 'word_problem' },
  },
] as const;
