import type { ProblemTemplate } from '../types';

export const EXPRESSIONS_TEMPLATES: readonly ProblemTemplate[] = [
  {
    id: 'expr_two_ops',
    operation: 'expressions',
    skillId: 'expressions.two-ops',
    standards: ['5.OA.A.1'],
    grades: [5],
    baseElo: 1050,
    digitCount: 1,
    domainConfig: { type: 'two_ops' },
  },
  {
    id: 'expr_parentheses',
    operation: 'expressions',
    skillId: 'expressions.parentheses',
    standards: ['5.OA.A.1'],
    grades: [5],
    baseElo: 1100,
    digitCount: 1,
    domainConfig: { type: 'parentheses' },
  },
  {
    id: 'expr_with_division',
    operation: 'expressions',
    skillId: 'expressions.with-division',
    standards: ['5.OA.A.1'],
    grades: [5],
    baseElo: 1100,
    digitCount: 1,
    domainConfig: { type: 'with_division' },
  },
  {
    id: 'expr_three_ops',
    operation: 'expressions',
    skillId: 'expressions.three-ops',
    standards: ['5.OA.A.1'],
    grades: [5],
    baseElo: 1200,
    digitCount: 1,
    domainConfig: { type: 'three_ops' },
  },
  {
    id: 'expr_nested_parens',
    operation: 'expressions',
    skillId: 'expressions.nested-parens',
    standards: ['5.OA.A.1'],
    grades: [5],
    baseElo: 1250,
    digitCount: 1,
    domainConfig: { type: 'nested_parens' },
  },
  {
    id: 'expr_one_step_eq',
    operation: 'expressions',
    skillId: 'expressions.one-step-equation',
    standards: ['6.EE.B.7'],
    grades: [6],
    baseElo: 1050,
    digitCount: 1,
    domainConfig: { type: 'one_step_equation' },
  },
  {
    id: 'expr_variable_eval',
    operation: 'expressions',
    skillId: 'expressions.variable-eval',
    standards: ['6.EE.A.2c'],
    grades: [6],
    baseElo: 1100,
    digitCount: 1,
    domainConfig: { type: 'variable_eval' },
  },
];
