import type { ProblemTemplate } from '../types';

/**
 * Fraction templates use addition operation for computation (numerator math)
 * but are tagged with 'fractions' operation for skill mapping.
 * The operands represent numerator values; the denominator is in domainConfig.
 */
export const FRACTIONS_TEMPLATES: readonly ProblemTemplate[] = [
  {
    id: 'frac_equal_parts',
    operation: 'fractions',
    skillId: 'fractions.equal-parts',
    standards: ['1.G.A.3'],
    grades: [1],
    operandRanges: [
      { min: 2, max: 4 },
      { min: 1, max: 1 },
    ],
    resultRange: { min: 2, max: 4 },
    baseElo: 800,
    digitCount: 1,
    domainConfig: { type: 'partitioning' },
  },
  {
    id: 'frac_halves_quarters',
    operation: 'fractions',
    skillId: 'fractions.halves-quarters',
    standards: ['2.G.A.3'],
    grades: [2],
    operandRanges: [
      { min: 1, max: 3 },
      { min: 2, max: 4 },
    ],
    resultRange: { min: 1, max: 3 },
    baseElo: 850,
    digitCount: 1,
    domainConfig: { type: 'identify' },
  },
  {
    id: 'frac_unit_fractions',
    operation: 'fractions',
    skillId: 'fractions.unit-fractions',
    standards: ['3.NF.A.1'],
    grades: [3],
    operandRanges: [
      { min: 1, max: 1 },
      { min: 2, max: 8 },
    ],
    resultRange: { min: 1, max: 1 },
    baseElo: 900,
    digitCount: 1,
    domainConfig: { type: 'unit' },
  },
  {
    id: 'frac_on_number_line',
    operation: 'fractions',
    skillId: 'fractions.on-number-line',
    standards: ['3.NF.A.2'],
    grades: [3],
    operandRanges: [
      { min: 1, max: 5 },
      { min: 2, max: 6 },
    ],
    resultRange: { min: 1, max: 5 },
    baseElo: 950,
    digitCount: 1,
    domainConfig: { type: 'number_line' },
  },
  {
    id: 'frac_equivalent',
    operation: 'fractions',
    skillId: 'fractions.equivalent',
    standards: ['3.NF.A.3'],
    grades: [3],
    operandRanges: [
      { min: 1, max: 6 },
      { min: 2, max: 8 },
    ],
    resultRange: { min: 1, max: 6 },
    baseElo: 1000,
    digitCount: 1,
    domainConfig: { type: 'equivalent' },
  },
  {
    id: 'frac_compare_same_denom',
    operation: 'fractions',
    skillId: 'fractions.compare-same-denom',
    standards: ['3.NF.A.3'],
    grades: [3],
    operandRanges: [
      { min: 1, max: 7 },
      { min: 1, max: 7 },
    ],
    resultRange: { min: 1, max: 7 },
    baseElo: 1020,
    digitCount: 1,
    domainConfig: { type: 'compare', constraint: 'same_denominator' },
  },
  {
    id: 'frac_compare_same_numer',
    operation: 'fractions',
    skillId: 'fractions.compare-same-numer',
    standards: ['3.NF.A.3'],
    grades: [3],
    operandRanges: [
      { min: 2, max: 8 },
      { min: 2, max: 8 },
    ],
    resultRange: { min: 2, max: 8 },
    baseElo: 1050,
    digitCount: 1,
    domainConfig: { type: 'compare', constraint: 'same_numerator' },
  },
  {
    id: 'frac_add_subtract_like_denom',
    operation: 'fractions',
    skillId: 'fractions.add-subtract-like-denom',
    standards: ['4.NF.B.3'],
    grades: [4],
    operandRanges: [
      { min: 1, max: 5 },
      { min: 1, max: 5 },
    ],
    resultRange: { min: 2, max: 10 },
    baseElo: 1100,
    digitCount: 1,
    domainConfig: { type: 'add_subtract', constraint: 'like_denominator' },
  },
  {
    id: 'frac_mixed_numbers',
    operation: 'fractions',
    skillId: 'fractions.mixed-numbers',
    standards: ['4.NF.B.3'],
    grades: [4],
    operandRanges: [
      { min: 1, max: 5 },
      { min: 1, max: 3 },
    ],
    resultRange: { min: 1, max: 5 },
    baseElo: 1150,
    digitCount: 1,
    domainConfig: { type: 'mixed_numbers' },
  },
  {
    id: 'frac_multiply_by_whole',
    operation: 'fractions',
    skillId: 'fractions.multiply-by-whole',
    standards: ['4.NF.B.4'],
    grades: [4],
    operandRanges: [
      { min: 1, max: 5 },
      { min: 2, max: 6 },
    ],
    resultRange: { min: 2, max: 30 },
    baseElo: 1180,
    digitCount: 1,
    domainConfig: { type: 'multiply_whole' },
  },
  {
    id: 'frac_add_subtract_unlike_denom',
    operation: 'fractions',
    skillId: 'fractions.add-subtract-unlike-denom',
    standards: ['5.NF.A.1'],
    grades: [5],
    operandRanges: [
      { min: 1, max: 5 },
      { min: 2, max: 6 },
    ],
    baseElo: 1200,
    digitCount: 1,
    domainConfig: { type: 'add_subtract_unlike' },
  },
  {
    id: 'frac_multiply_fractions',
    operation: 'fractions',
    skillId: 'fractions.multiply-fractions',
    standards: ['5.NF.B.4'],
    grades: [5],
    operandRanges: [
      { min: 1, max: 5 },
      { min: 2, max: 6 },
    ],
    baseElo: 1250,
    digitCount: 1,
    domainConfig: { type: 'multiply_fractions' },
  },
  {
    id: 'frac_divide_unit_fraction',
    operation: 'fractions',
    skillId: 'fractions.divide-unit-fraction',
    standards: ['5.NF.B.7'],
    grades: [5],
    operandRanges: [
      { min: 2, max: 6 },
      { min: 2, max: 5 },
    ],
    baseElo: 1300,
    digitCount: 1,
    domainConfig: { type: 'divide_unit_fraction' },
  },
  {
    id: 'frac_divide_fractions',
    operation: 'fractions',
    skillId: 'fractions.divide-fractions',
    standards: ['6.NS.A.1'],
    grades: [6],
    operandRanges: [
      { min: 1, max: 5 },
      { min: 2, max: 6 },
    ],
    baseElo: 1400,
    digitCount: 1,
    domainConfig: { type: 'divide_fractions' },
  },
];
