import type { ProblemTemplate } from '../types';

export const GEOMETRY_TEMPLATES: readonly ProblemTemplate[] = [
  {
    id: 'geom_complementary',
    operation: 'geometry',
    skillId: 'geometry.complementary-angles',
    standards: ['7.G.B.5'],
    grades: [7],
    baseElo: 1000,
    digitCount: 2,
    domainConfig: { type: 'complementary_angles' },
  },
  {
    id: 'geom_supplementary',
    operation: 'geometry',
    skillId: 'geometry.supplementary-angles',
    standards: ['7.G.B.5'],
    grades: [7],
    baseElo: 1050,
    digitCount: 2,
    domainConfig: { type: 'supplementary_angles' },
  },
  {
    id: 'geom_circle_area',
    operation: 'geometry',
    skillId: 'geometry.circle-area',
    standards: ['7.G.B.4'],
    grades: [7],
    baseElo: 1100,
    digitCount: 2,
    domainConfig: { type: 'circle_area' },
  },
  {
    id: 'geom_circle_circumference',
    operation: 'geometry',
    skillId: 'geometry.circle-circumference',
    standards: ['7.G.B.4'],
    grades: [7],
    baseElo: 1050,
    digitCount: 2,
    domainConfig: { type: 'circle_circumference' },
  },
  {
    id: 'geom_pythagorean',
    operation: 'geometry',
    skillId: 'geometry.pythagorean',
    standards: ['8.G.B.7'],
    grades: [8],
    baseElo: 1200,
    digitCount: 2,
    domainConfig: { type: 'pythagorean' },
  },
  {
    id: 'geom_slope',
    operation: 'geometry',
    skillId: 'geometry.slope',
    standards: ['8.EE.B.6'],
    grades: [8],
    baseElo: 1200,
    digitCount: 2,
    domainConfig: { type: 'slope' },
  },
];
