import type { ProblemTemplate } from '../types';

export const LINEAR_EQUATIONS_TEMPLATES: readonly ProblemTemplate[] = [
  {
    id: 'lin_one_step_add_sub',
    operation: 'linear_equations',
    skillId: 'one_step_addition',
    grades: [8],
    baseElo: 1000,
    digitCount: 1,
    distractorStrategy: 'domain_specific',
    standards: ['8.EE.C.7b'],
    domainConfig: { type: 'one_step_add_sub' },
  },
  {
    id: 'lin_one_step_mul_div',
    operation: 'linear_equations',
    skillId: 'one_step_multiplication',
    grades: [8],
    baseElo: 1050,
    digitCount: 1,
    distractorStrategy: 'domain_specific',
    standards: ['8.EE.C.7b'],
    domainConfig: { type: 'one_step_mul_div' },
  },
  {
    id: 'lin_two_step_add_mul',
    operation: 'linear_equations',
    skillId: 'two_step_add_mul',
    grades: [8],
    baseElo: 1075,
    digitCount: 1,
    distractorStrategy: 'domain_specific',
    standards: ['8.EE.C.7b'],
    domainConfig: { type: 'two_step_add_mul' },
  },
  {
    id: 'lin_two_step_sub_div',
    operation: 'linear_equations',
    skillId: 'two_step_sub_div',
    grades: [8],
    baseElo: 1100,
    digitCount: 1,
    distractorStrategy: 'domain_specific',
    standards: ['8.EE.C.7b'],
    domainConfig: { type: 'two_step_sub_div' },
  },
  {
    id: 'lin_two_step_mixed',
    operation: 'linear_equations',
    skillId: 'two_step_mixed',
    grades: [8],
    baseElo: 1125,
    digitCount: 1,
    distractorStrategy: 'domain_specific',
    standards: ['8.EE.C.7b'],
    domainConfig: { type: 'two_step_mixed' },
  },
  {
    id: 'lin_multi_step',
    operation: 'linear_equations',
    skillId: 'multi_step',
    grades: [9],
    baseElo: 1200,
    digitCount: 1,
    distractorStrategy: 'domain_specific',
    standards: ['8.EE.C.7a'],
    domainConfig: { type: 'multi_step' },
  },
  {
    id: 'lin_negative_solution',
    operation: 'linear_equations',
    skillId: 'negative_solution',
    grades: [8],
    baseElo: 1075,
    digitCount: 1,
    distractorStrategy: 'domain_specific',
    standards: ['8.EE.C.7b'],
    domainConfig: { type: 'negative_solution' },
  },
  {
    id: 'lin_word_problem',
    operation: 'linear_equations',
    skillId: 'word_problem',
    grades: [9],
    baseElo: 1150,
    digitCount: 1,
    distractorStrategy: 'domain_specific',
    standards: ['8.EE.C.7'],
    domainConfig: { type: 'word_problem' },
  },
];
