import type { ProblemTemplate } from '../types';

export const MEASUREMENT_TEMPLATES: readonly ProblemTemplate[] = [
  {
    id: 'meas_convert_down',
    operation: 'measurement',
    skillId: 'measurement.convert-down',
    standards: ['4.MD.A.1'],
    grades: [4],
    baseElo: 950,
    digitCount: 2,
    domainConfig: { type: 'convert_down' },
  },
  {
    id: 'meas_convert_up',
    operation: 'measurement',
    skillId: 'measurement.convert-up',
    standards: ['4.MD.A.1'],
    grades: [4],
    baseElo: 1000,
    digitCount: 2,
    domainConfig: { type: 'convert_up' },
  },
  {
    id: 'meas_compare',
    operation: 'measurement',
    skillId: 'measurement.compare',
    standards: ['4.MD.A.2'],
    grades: [4, 5],
    baseElo: 1050,
    digitCount: 2,
    domainConfig: { type: 'compare' },
  },
  {
    id: 'meas_metric',
    operation: 'measurement',
    skillId: 'measurement.metric',
    standards: ['5.MD.A.1'],
    grades: [5],
    baseElo: 1050,
    digitCount: 3,
    domainConfig: { type: 'metric' },
  },
  {
    id: 'meas_multi_step',
    operation: 'measurement',
    skillId: 'measurement.multi-step',
    standards: ['5.MD.A.1'],
    grades: [5],
    baseElo: 1150,
    digitCount: 3,
    domainConfig: { type: 'multi_step' },
  },
];
