import type { ProblemTemplate } from '../types';

export const MULTIPLICATION_TEMPLATES: readonly ProblemTemplate[] = [
  {
    id: 'mult_equal_groups',
    operation: 'multiplication',
    skillId: 'multiplication.equal-groups',
    standards: ['2.OA.C.4'],
    grades: [2],
    operandRanges: [
      { min: 2, max: 5 },
      { min: 2, max: 5 },
    ],
    resultRange: { min: 4, max: 25 },
    baseElo: 850,
    digitCount: 1,
  },
  {
    id: 'mult_arrays',
    operation: 'multiplication',
    skillId: 'multiplication.arrays',
    standards: ['2.OA.C.4'],
    grades: [2],
    operandRanges: [
      { min: 2, max: 5 },
      { min: 2, max: 5 },
    ],
    resultRange: { min: 4, max: 25 },
    baseElo: 870,
    digitCount: 1,
  },
  {
    id: 'mult_repeated_addition',
    operation: 'multiplication',
    skillId: 'multiplication.repeated-addition',
    standards: ['2.OA.C.4'],
    grades: [2],
    operandRanges: [
      { min: 2, max: 5 },
      { min: 2, max: 5 },
    ],
    resultRange: { min: 4, max: 25 },
    baseElo: 870,
    digitCount: 1,
  },
  {
    id: 'mult_facts_2_5_10',
    operation: 'multiplication',
    skillId: 'multiplication.facts-2-5-10',
    standards: ['3.OA.C.7'],
    grades: [3],
    operandRanges: [
      { min: 2, max: 10 },
      { min: 2, max: 10 },
    ],
    resultRange: { min: 4, max: 100 },
    baseElo: 900,
    digitCount: 1,
  },
  {
    id: 'mult_facts_3_4_6',
    operation: 'multiplication',
    skillId: 'multiplication.facts-3-4-6',
    standards: ['3.OA.C.7'],
    grades: [3],
    operandRanges: [
      { min: 3, max: 9 },
      { min: 3, max: 9 },
    ],
    resultRange: { min: 9, max: 81 },
    baseElo: 950,
    digitCount: 1,
  },
  {
    id: 'mult_facts_7_8_9',
    operation: 'multiplication',
    skillId: 'multiplication.facts-7-8-9',
    standards: ['3.OA.C.7'],
    grades: [3],
    operandRanges: [
      { min: 2, max: 9 },
      { min: 7, max: 9 },
    ],
    resultRange: { min: 14, max: 81 },
    baseElo: 1000,
    digitCount: 1,
  },
  {
    id: 'mult_by_10_100',
    operation: 'multiplication',
    skillId: 'multiplication.by-10-100',
    standards: ['3.NBT.A.3'],
    grades: [3],
    operandRanges: [
      { min: 1, max: 9 },
      { min: 10, max: 100 },
    ],
    resultRange: { min: 10, max: 900 },
    baseElo: 920,
    digitCount: 1,
  },
  {
    id: 'mult_two_by_one',
    operation: 'multiplication',
    skillId: 'multiplication.two-by-one',
    standards: ['4.NBT.B.5'],
    grades: [4],
    operandRanges: [
      { min: 10, max: 99 },
      { min: 2, max: 9 },
    ],
    resultRange: { min: 20, max: 891 },
    baseElo: 1050,
    digitCount: 2,
  },
  {
    id: 'mult_two_by_two',
    operation: 'multiplication',
    skillId: 'multiplication.two-by-two',
    standards: ['4.NBT.B.5'],
    grades: [4],
    operandRanges: [
      { min: 10, max: 99 },
      { min: 10, max: 99 },
    ],
    resultRange: { min: 100, max: 9801 },
    baseElo: 1150,
    digitCount: 2,
  },
  {
    id: 'mult_four_by_one',
    operation: 'multiplication',
    skillId: 'multiplication.four-by-one',
    standards: ['4.NBT.B.5'],
    grades: [4],
    operandRanges: [
      { min: 100, max: 9999 },
      { min: 2, max: 9 },
    ],
    resultRange: { min: 200, max: 89991 },
    baseElo: 1200,
    digitCount: 4,
  },
  {
    id: 'mult_three_by_two',
    operation: 'multiplication',
    skillId: 'multiplication.three-by-two',
    standards: ['5.NBT.B.5'],
    grades: [5],
    operandRanges: [
      { min: 100, max: 500 },
      { min: 10, max: 50 },
    ],
    resultRange: { min: 1000, max: 25000 },
    baseElo: 1100,
    digitCount: 3,
  },
];
