import type { ProblemTemplate } from '../types';

/**
 * Place value templates. These use addition as the underlying computation
 * but are tagged with 'place_value' operation for skill mapping.
 */
export const PLACE_VALUE_TEMPLATES: readonly ProblemTemplate[] = [
  {
    id: 'pv_ones_tens',
    operation: 'place_value',
    skillId: 'place-value.ones-tens',
    standards: ['1.NBT.B.2'],
    grades: [1],
    operandRanges: [
      { min: 10, max: 99 },
      { min: 1, max: 1 },
    ],
    resultRange: { min: 0, max: 9 },
    baseElo: 800,
    digitCount: 2,
    domainConfig: { type: 'decompose' },
  },
  {
    id: 'pv_hundreds',
    operation: 'place_value',
    skillId: 'place-value.hundreds',
    standards: ['2.NBT.A.1'],
    grades: [2],
    operandRanges: [
      { min: 100, max: 999 },
      { min: 1, max: 1 },
    ],
    resultRange: { min: 1, max: 9 },
    baseElo: 850,
    digitCount: 3,
    domainConfig: { type: 'identify_digit' },
  },
  {
    id: 'pv_to_1000',
    operation: 'place_value',
    skillId: 'place-value.to-1000',
    standards: ['2.NBT.A.3'],
    grades: [2],
    operandRanges: [
      { min: 100, max: 999 },
      { min: 1, max: 1 },
    ],
    resultRange: { min: 100, max: 999 },
    baseElo: 880,
    digitCount: 3,
    domainConfig: { type: 'read_write' },
  },
  {
    id: 'pv_comparing',
    operation: 'place_value',
    skillId: 'place-value.comparing',
    standards: ['2.NBT.A.4'],
    grades: [2],
    operandRanges: [
      { min: 10, max: 999 },
      { min: 10, max: 999 },
    ],
    resultRange: { min: 10, max: 999 },
    baseElo: 900,
    digitCount: 3,
    domainConfig: { type: 'compare' },
  },
  {
    id: 'pv_skip_counting',
    operation: 'place_value',
    skillId: 'place-value.skip-counting',
    standards: ['2.NBT.A.2'],
    grades: [2],
    operandRanges: [
      { min: 2, max: 100 },
      { min: 2, max: 10 },
    ],
    resultRange: { min: 4, max: 200 },
    baseElo: 870,
    digitCount: 2,
    domainConfig: { type: 'skip_count' },
  },
  {
    id: 'pv_rounding_10_100',
    operation: 'place_value',
    skillId: 'place-value.rounding-10-100',
    standards: ['3.NBT.A.1'],
    grades: [3],
    operandRanges: [
      { min: 10, max: 999 },
      { min: 10, max: 100 },
    ],
    resultRange: { min: 10, max: 1000 },
    baseElo: 950,
    digitCount: 3,
    domainConfig: { type: 'rounding' },
  },
  {
    id: 'pv_to_10000',
    operation: 'place_value',
    skillId: 'place-value.to-10000',
    standards: ['4.NBT.A.2'],
    grades: [4],
    operandRanges: [
      { min: 1000, max: 9999 },
      { min: 1, max: 1 },
    ],
    resultRange: { min: 1000, max: 9999 },
    baseElo: 1050,
    digitCount: 4,
    domainConfig: { type: 'identify_digit' },
  },
  {
    id: 'pv_expanded_form',
    operation: 'place_value',
    skillId: 'place-value.expanded-form',
    standards: ['4.NBT.A.2'],
    grades: [4],
    operandRanges: [
      { min: 1000, max: 9999 },
      { min: 1, max: 1 },
    ],
    resultRange: { min: 1000, max: 9999 },
    baseElo: 1100,
    digitCount: 4,
    domainConfig: { type: 'expanded_form' },
  },
  {
    id: 'pv_decimal_identify',
    operation: 'place_value',
    skillId: 'place-value.decimal-identify',
    standards: ['5.NBT.A.1'],
    grades: [5],
    baseElo: 1050,
    digitCount: 2,
    domainConfig: { type: 'decimal_identify' },
  },
  {
    id: 'pv_decimal_decompose',
    operation: 'place_value',
    skillId: 'place-value.decimal-decompose',
    standards: ['5.NBT.A.1'],
    grades: [5],
    baseElo: 1100,
    digitCount: 2,
    domainConfig: { type: 'decimal_decompose' },
  },
  {
    id: 'pv_decimal_compare',
    operation: 'place_value',
    skillId: 'place-value.decimal-compare',
    standards: ['5.NBT.A.3b'],
    grades: [5],
    baseElo: 1050,
    digitCount: 2,
    domainConfig: { type: 'decimal_compare' },
  },
  {
    id: 'pv_decimal_rounding',
    operation: 'place_value',
    skillId: 'place-value.decimal-rounding',
    standards: ['5.NBT.A.4'],
    grades: [5],
    baseElo: 1100,
    digitCount: 2,
    domainConfig: { type: 'decimal_rounding' },
  },
];
