import type { ProblemTemplate } from '../types';

export const POLYNOMIALS_TEMPLATES: readonly ProblemTemplate[] = [
  {
    id: 'poly_foil_expansion',
    operation: 'polynomials',
    skillId: 'foil_expansion',
    grades: [9],
    baseElo: 1000,
    digitCount: 2,
    distractorStrategy: 'domain_specific',
    standards: ['HSA-APR.A.1'],
    domainConfig: { type: 'foil_expansion' },
  },
  {
    id: 'poly_evaluation',
    operation: 'polynomials',
    skillId: 'poly_evaluation',
    grades: [9],
    baseElo: 950,
    digitCount: 2,
    distractorStrategy: 'domain_specific',
    standards: ['HSA-APR.A.1'],
    domainConfig: { type: 'poly_evaluation' },
  },
  {
    id: 'poly_gcf_factoring',
    operation: 'polynomials',
    skillId: 'gcf_factoring',
    grades: [9],
    baseElo: 1050,
    digitCount: 2,
    distractorStrategy: 'domain_specific',
    standards: ['HSA-SSE.A.2'],
    domainConfig: { type: 'gcf_factoring' },
  },
  {
    id: 'poly_diff_of_squares',
    operation: 'polynomials',
    skillId: 'diff_of_squares',
    grades: [10],
    baseElo: 1100,
    digitCount: 2,
    distractorStrategy: 'domain_specific',
    standards: ['HSA-SSE.A.2'],
    domainConfig: { type: 'diff_of_squares' },
  },
  {
    id: 'poly_combined_operations',
    operation: 'polynomials',
    skillId: 'combined_operations',
    grades: [10],
    baseElo: 1150,
    digitCount: 2,
    distractorStrategy: 'domain_specific',
    standards: ['HSA-APR.A.1'],
    domainConfig: { type: 'combined_operations' },
  },
  {
    id: 'poly_word_problem',
    operation: 'polynomials',
    skillId: 'poly_word_problem',
    grades: [10],
    baseElo: 1200,
    digitCount: 2,
    distractorStrategy: 'domain_specific',
    standards: ['HSA-SSE.A.2'],
    domainConfig: { type: 'word_problem' },
  },
] as const;
