import type { ProblemTemplate } from '../types';

export const QUADRATIC_EQUATIONS_TEMPLATES: readonly ProblemTemplate[] = [
  {
    id: 'quad_factoring_monic',
    operation: 'quadratic_equations',
    skillId: 'factoring_monic',
    grades: [9],
    baseElo: 1050,
    digitCount: 2,
    distractorStrategy: 'domain_specific',
    standards: ['HSA-REI.B.4'],
    domainConfig: { type: 'factoring_monic' },
  },
  {
    id: 'quad_factoring_leading_coeff',
    operation: 'quadratic_equations',
    skillId: 'factoring_leading_coeff',
    grades: [9],
    baseElo: 1100,
    digitCount: 2,
    distractorStrategy: 'domain_specific',
    standards: ['HSA-REI.B.4'],
    domainConfig: { type: 'factoring_leading_coeff' },
  },
  {
    id: 'quad_formula_simple',
    operation: 'quadratic_equations',
    skillId: 'quadratic_formula_simple',
    grades: [9],
    baseElo: 1100,
    digitCount: 2,
    distractorStrategy: 'domain_specific',
    standards: ['HSA-REI.B.4'],
    domainConfig: { type: 'quadratic_formula_simple' },
  },
  {
    id: 'quad_formula_rational',
    operation: 'quadratic_equations',
    skillId: 'quadratic_formula_rational',
    grades: [10],
    baseElo: 1150,
    digitCount: 2,
    distractorStrategy: 'domain_specific',
    standards: ['HSA-REI.B.4'],
    domainConfig: { type: 'quadratic_formula_rational' },
  },
  {
    id: 'quad_completing_square',
    operation: 'quadratic_equations',
    skillId: 'completing_the_square',
    grades: [10],
    baseElo: 1150,
    digitCount: 2,
    distractorStrategy: 'domain_specific',
    standards: ['HSA-REI.B.4'],
    domainConfig: { type: 'completing_the_square' },
  },
  {
    id: 'quad_word_problem',
    operation: 'quadratic_equations',
    skillId: 'quad_word_problem',
    grades: [10],
    baseElo: 1100,
    digitCount: 2,
    distractorStrategy: 'domain_specific',
    standards: ['HSA-REI.B.4'],
    domainConfig: { type: 'word_problem' },
  },
] as const;
