import type { ProblemTemplate } from '../types';

export const RATIOS_TEMPLATES: readonly ProblemTemplate[] = [
  {
    id: 'ratio_simplify',
    operation: 'ratios',
    skillId: 'ratios.simplify',
    standards: ['6.RP.A.1'],
    grades: [6],
    baseElo: 1050,
    digitCount: 2,
    domainConfig: { type: 'simplify' },
  },
  {
    id: 'ratio_equivalent',
    operation: 'ratios',
    skillId: 'ratios.equivalent',
    standards: ['6.RP.A.3'],
    grades: [6],
    baseElo: 1100,
    digitCount: 2,
    domainConfig: { type: 'equivalent' },
  },
  {
    id: 'ratio_unit_rate',
    operation: 'ratios',
    skillId: 'ratios.unit-rate',
    standards: ['6.RP.A.2'],
    grades: [6],
    baseElo: 1050,
    digitCount: 2,
    domainConfig: { type: 'unit_rate' },
  },
  {
    id: 'ratio_percent_of',
    operation: 'ratios',
    skillId: 'ratios.percent-of',
    standards: ['6.RP.A.3c'],
    grades: [6],
    baseElo: 1100,
    digitCount: 2,
    domainConfig: { type: 'percent_of' },
  },
  {
    id: 'ratio_fraction_to_percent',
    operation: 'ratios',
    skillId: 'ratios.fraction-to-percent',
    standards: ['6.RP.A.3c'],
    grades: [6],
    baseElo: 1100,
    digitCount: 2,
    domainConfig: { type: 'fraction_to_percent' },
  },
  {
    id: 'ratio_percent_change',
    operation: 'ratios',
    skillId: 'ratios.percent-change',
    standards: ['7.RP.A.3'],
    grades: [7],
    baseElo: 1200,
    digitCount: 2,
    domainConfig: { type: 'percent_change' },
  },
  {
    id: 'ratio_proportion',
    operation: 'ratios',
    skillId: 'ratios.proportion',
    standards: ['7.RP.A.2'],
    grades: [7],
    baseElo: 1150,
    digitCount: 2,
    domainConfig: { type: 'proportion' },
  },
  {
    id: 'ratio_percent_find_whole',
    operation: 'ratios',
    skillId: 'ratios.percent-find-whole',
    standards: ['7.RP.A.3'],
    grades: [7],
    baseElo: 1150,
    digitCount: 2,
    domainConfig: { type: 'percent_find_whole' },
  },
  {
    id: 'ratio_scale_drawing',
    operation: 'ratios',
    skillId: 'ratios.scale-drawing',
    standards: ['7.G.A.1'],
    grades: [7],
    baseElo: 1150,
    digitCount: 2,
    domainConfig: { type: 'scale_drawing' },
  },
];
