import type { ProblemTemplate } from '../types';

export const SEQUENCES_SERIES_TEMPLATES: readonly ProblemTemplate[] = [
  {
    id: 'seq_arithmetic_next',
    operation: 'sequences_series',
    skillId: 'arithmetic_next_term',
    grades: [9],
    baseElo: 1000,
    digitCount: 2,
    distractorStrategy: 'domain_specific',
    standards: ['HSF-BF.A.1a'],
    domainConfig: { type: 'arithmetic_next_term' },
  },
  {
    id: 'seq_arithmetic_nth',
    operation: 'sequences_series',
    skillId: 'arithmetic_nth_term',
    grades: [9],
    baseElo: 1050,
    digitCount: 2,
    distractorStrategy: 'domain_specific',
    standards: ['HSF-BF.A.1a'],
    domainConfig: { type: 'arithmetic_nth_term' },
  },
  {
    id: 'seq_geometric_next',
    operation: 'sequences_series',
    skillId: 'geometric_next_term',
    grades: [10],
    baseElo: 1100,
    digitCount: 2,
    distractorStrategy: 'domain_specific',
    standards: ['HSF-BF.A.1a'],
    domainConfig: { type: 'geometric_next_term' },
  },
  {
    id: 'seq_geometric_nth',
    operation: 'sequences_series',
    skillId: 'geometric_nth_term',
    grades: [10],
    baseElo: 1150,
    digitCount: 2,
    distractorStrategy: 'domain_specific',
    standards: ['HSF-BF.A.1a'],
    domainConfig: { type: 'geometric_nth_term' },
  },
  {
    id: 'seq_word_problem',
    operation: 'sequences_series',
    skillId: 'seq_word_problem',
    grades: [10],
    baseElo: 1100,
    digitCount: 2,
    distractorStrategy: 'domain_specific',
    standards: ['HSF-BF.A.1a'],
    domainConfig: { type: 'word_problem' },
  },
] as const;
