import type { ProblemTemplate } from '../types';

export const STATISTICS_HS_TEMPLATES: readonly ProblemTemplate[] = [
  {
    id: 'stats_stddev_concept',
    operation: 'statistics_hs',
    skillId: 'stats_stddev_concept',
    grades: [9],
    baseElo: 1000,
    digitCount: 1,
    distractorStrategy: 'domain_specific',
    standards: ['HSS-ID.A.2'],
    domainConfig: { type: 'stddev_concept' },
  },
  {
    id: 'stats_normal_rule',
    operation: 'statistics_hs',
    skillId: 'stats_normal_rule',
    grades: [9],
    baseElo: 1050,
    digitCount: 1,
    distractorStrategy: 'domain_specific',
    standards: ['HSS-ID.A.4'],
    domainConfig: { type: 'normal_rule' },
  },
  {
    id: 'stats_zscore',
    operation: 'statistics_hs',
    skillId: 'stats_zscore',
    grades: [10],
    baseElo: 1100,
    digitCount: 1,
    distractorStrategy: 'domain_specific',
    standards: ['HSS-ID.A.4'],
    domainConfig: { type: 'zscore' },
  },
  {
    id: 'stats_percentile',
    operation: 'statistics_hs',
    skillId: 'stats_percentile',
    grades: [10],
    baseElo: 1150,
    digitCount: 1,
    distractorStrategy: 'domain_specific',
    standards: ['HSS-ID.A.4'],
    domainConfig: { type: 'percentile' },
  },
  {
    id: 'stats_word_problem',
    operation: 'statistics_hs',
    skillId: 'stats_word_problem',
    grades: [10],
    baseElo: 1100,
    digitCount: 1,
    distractorStrategy: 'domain_specific',
    standards: ['HSS-ID.A.4'],
    domainConfig: { type: 'word_problem' },
  },
] as const;
