import type { ProblemTemplate } from '../types';

export const SUBTRACTION_TEMPLATES: readonly ProblemTemplate[] = [
  {
    id: 'sub_single_digit_no_borrow',
    operation: 'subtraction',
    skillId: 'subtraction.single-digit.no-borrow',
    standards: ['1.OA.C.6'],
    grades: [1],
    operandRanges: [
      { min: 2, max: 9 },
      { min: 1, max: 8 },
    ],
    resultRange: { min: 1, max: 8 },
    requiresBorrow: false,
    baseElo: 800,
    digitCount: 1,
  },
  {
    id: 'sub_within_20_no_borrow',
    operation: 'subtraction',
    skillId: 'subtraction.within-20.no-borrow',
    standards: ['1.OA.C.6'],
    grades: [1],
    operandRanges: [
      { min: 10, max: 19 },
      { min: 1, max: 9 },
    ],
    resultRange: { min: 1, max: 18 },
    requiresBorrow: false,
    baseElo: 850,
    digitCount: 2,
  },
  {
    id: 'sub_within_20_with_borrow',
    operation: 'subtraction',
    skillId: 'subtraction.within-20.with-borrow',
    standards: ['1.OA.C.6'],
    grades: [1],
    operandRanges: [
      { min: 11, max: 18 },
      { min: 2, max: 9 },
    ],
    resultRange: { min: 2, max: 16 },
    requiresBorrow: true,
    baseElo: 920,
    digitCount: 2,
  },
  {
    id: 'sub_two_digit_no_borrow',
    operation: 'subtraction',
    skillId: 'subtraction.two-digit.no-borrow',
    standards: ['2.NBT.B.5'],
    grades: [2, 3],
    operandRanges: [
      { min: 20, max: 99 },
      { min: 10, max: 89 },
    ],
    resultRange: { min: 1, max: 89 },
    requiresBorrow: false,
    baseElo: 1000,
    digitCount: 2,
  },
  {
    id: 'sub_two_digit_with_borrow',
    operation: 'subtraction',
    skillId: 'subtraction.two-digit.with-borrow',
    standards: ['2.NBT.B.5'],
    grades: [2, 3],
    operandRanges: [
      { min: 20, max: 99 },
      { min: 10, max: 89 },
    ],
    resultRange: { min: 1, max: 89 },
    requiresBorrow: true,
    baseElo: 1080,
    digitCount: 2,
  },
  {
    id: 'sub_three_digit_no_borrow',
    operation: 'subtraction',
    skillId: 'subtraction.three-digit.no-borrow',
    standards: ['3.NBT.A.2'],
    grades: [3],
    operandRanges: [
      { min: 200, max: 999 },
      { min: 100, max: 899 },
    ],
    resultRange: { min: 1, max: 899 },
    requiresBorrow: false,
    baseElo: 1150,
    digitCount: 3,
  },
  {
    id: 'sub_three_digit_with_borrow',
    operation: 'subtraction',
    skillId: 'subtraction.three-digit.with-borrow',
    standards: ['3.NBT.A.2'],
    grades: [3],
    operandRanges: [
      { min: 200, max: 999 },
      { min: 100, max: 899 },
    ],
    resultRange: { min: 1, max: 899 },
    requiresBorrow: true,
    baseElo: 1250,
    digitCount: 3,
  },
  {
    id: 'sub_four_digit_with_borrow',
    operation: 'subtraction',
    skillId: 'subtraction.four-digit.with-borrow',
    standards: ['4.NBT.B.4'],
    grades: [4],
    operandRanges: [
      { min: 2000, max: 9999 },
      { min: 1000, max: 8999 },
    ],
    resultRange: { min: 1, max: 8999 },
    requiresBorrow: true,
    baseElo: 1350,
    digitCount: 4,
  },
];
