import type { ProblemTemplate } from '../types';

export const SYSTEMS_EQUATIONS_TEMPLATES: readonly ProblemTemplate[] = [
  {
    id: 'sys_substitution_simple',
    operation: 'systems_equations',
    skillId: 'substitution_simple',
    grades: [9],
    baseElo: 1050,
    digitCount: 2,
    distractorStrategy: 'domain_specific',
    standards: ['HSA-REI.C.6'],
    domainConfig: { type: 'substitution_simple' },
  },
  {
    id: 'sys_substitution_general',
    operation: 'systems_equations',
    skillId: 'substitution_general',
    grades: [9],
    baseElo: 1100,
    digitCount: 2,
    distractorStrategy: 'domain_specific',
    standards: ['HSA-REI.C.6'],
    domainConfig: { type: 'substitution_general' },
  },
  {
    id: 'sys_elimination_add',
    operation: 'systems_equations',
    skillId: 'elimination_add',
    grades: [9],
    baseElo: 1100,
    digitCount: 2,
    distractorStrategy: 'domain_specific',
    standards: ['HSA-REI.C.6'],
    domainConfig: { type: 'elimination_add' },
  },
  {
    id: 'sys_elimination_multiply',
    operation: 'systems_equations',
    skillId: 'elimination_multiply',
    grades: [10],
    baseElo: 1150,
    digitCount: 2,
    distractorStrategy: 'domain_specific',
    standards: ['HSA-REI.C.6'],
    domainConfig: { type: 'elimination_multiply' },
  },
  {
    id: 'sys_word_problem',
    operation: 'systems_equations',
    skillId: 'sys_word_problem',
    grades: [10],
    baseElo: 1100,
    digitCount: 2,
    distractorStrategy: 'domain_specific',
    standards: ['HSA-REI.C.6'],
    domainConfig: { type: 'word_problem' },
  },
] as const;
