import type { SkillDefinition } from '../types';

export const ADDITION_SKILLS: readonly SkillDefinition[] = [
  {
    id: 'addition.single-digit.no-carry',
    name: 'Add within 10',
    operation: 'addition',
    grade: 1,
    standards: ['1.OA.C.6'],
    prerequisites: [],
  },
  {
    id: 'addition.within-20.no-carry',
    name: 'Add within 20 (no carry)',
    operation: 'addition',
    grade: 1,
    standards: ['1.OA.C.6'],
    prerequisites: ['addition.single-digit.no-carry'],
  },
  {
    id: 'addition.within-20.with-carry',
    name: 'Add within 20 (with carry)',
    operation: 'addition',
    grade: 1,
    standards: ['1.OA.C.6'],
    prerequisites: ['addition.within-20.no-carry'],
  },
  {
    id: 'addition.two-digit.no-carry',
    name: 'Add two-digit (no carry)',
    operation: 'addition',
    grade: 2,
    standards: ['2.NBT.B.5'],
    prerequisites: ['addition.within-20.with-carry'],
  },
  {
    id: 'addition.two-digit.with-carry',
    name: 'Add two-digit (with carry)',
    operation: 'addition',
    grade: 2,
    standards: ['2.NBT.B.5'],
    prerequisites: ['addition.two-digit.no-carry'],
  },
  {
    id: 'addition.three-digit.no-carry',
    name: 'Add three-digit (no carry)',
    operation: 'addition',
    grade: 3,
    standards: ['3.NBT.A.2'],
    prerequisites: ['addition.two-digit.with-carry'],
  },
  {
    id: 'addition.three-digit.with-carry',
    name: 'Add three-digit (with carry)',
    operation: 'addition',
    grade: 3,
    standards: ['3.NBT.A.2'],
    prerequisites: ['addition.three-digit.no-carry'],
  },
  {
    id: 'addition.four-digit.no-carry',
    name: 'Add four-digit (no carry)',
    operation: 'addition',
    grade: 4,
    standards: ['4.NBT.B.4'],
    prerequisites: ['addition.three-digit.with-carry'],
  },
  {
    id: 'addition.four-digit.with-carry',
    name: 'Add four-digit (with carry)',
    operation: 'addition',
    grade: 4,
    standards: ['4.NBT.B.4'],
    prerequisites: ['addition.four-digit.no-carry'],
  },
];
