import type { SkillDefinition } from '../types';

export const FRACTIONS_SKILLS: readonly SkillDefinition[] = [
  {
    id: 'fractions.equal-parts',
    name: 'Equal partitioning',
    operation: 'fractions',
    grade: 1,
    standards: ['1.G.A.3'],
    prerequisites: [],
  },
  {
    id: 'fractions.halves-quarters',
    name: 'Halves, quarters, thirds',
    operation: 'fractions',
    grade: 2,
    standards: ['2.G.A.3'],
    prerequisites: ['fractions.equal-parts'],
  },
  {
    id: 'fractions.unit-fractions',
    name: 'Unit fractions',
    operation: 'fractions',
    grade: 3,
    standards: ['3.NF.A.1'],
    prerequisites: ['fractions.halves-quarters'],
  },
  {
    id: 'fractions.on-number-line',
    name: 'Fractions on number line',
    operation: 'fractions',
    grade: 3,
    standards: ['3.NF.A.2'],
    prerequisites: ['fractions.unit-fractions'],
  },
  {
    id: 'fractions.equivalent',
    name: 'Equivalent fractions',
    operation: 'fractions',
    grade: 3,
    standards: ['3.NF.A.3'],
    prerequisites: ['fractions.on-number-line'],
  },
  {
    id: 'fractions.compare-same-denom',
    name: 'Compare fractions (same denominator)',
    operation: 'fractions',
    grade: 3,
    standards: ['3.NF.A.3'],
    prerequisites: ['fractions.equivalent'],
  },
  {
    id: 'fractions.compare-same-numer',
    name: 'Compare fractions (same numerator)',
    operation: 'fractions',
    grade: 3,
    standards: ['3.NF.A.3'],
    prerequisites: ['fractions.compare-same-denom'],
  },
  {
    id: 'fractions.add-subtract-like-denom',
    name: 'Add/subtract fractions (same denominator)',
    operation: 'fractions',
    grade: 4,
    standards: ['4.NF.B.3'],
    prerequisites: ['fractions.compare-same-numer'],
  },
  {
    id: 'fractions.mixed-numbers',
    name: 'Mixed numbers',
    operation: 'fractions',
    grade: 4,
    standards: ['4.NF.B.3'],
    prerequisites: ['fractions.add-subtract-like-denom'],
  },
  {
    id: 'fractions.multiply-by-whole',
    name: 'Fraction × whole number',
    operation: 'fractions',
    grade: 4,
    standards: ['4.NF.B.4'],
    prerequisites: ['fractions.add-subtract-like-denom'],
  },
  {
    id: 'fractions.add-subtract-unlike-denom',
    name: 'Add/subtract fractions (unlike denominators)',
    operation: 'fractions',
    grade: 5,
    standards: ['5.NF.A.1'],
    prerequisites: ['fractions.add-subtract-like-denom', 'fractions.equivalent'],
  },
  {
    id: 'fractions.multiply-fractions',
    name: 'Multiply fractions',
    operation: 'fractions',
    grade: 5,
    standards: ['5.NF.B.4'],
    prerequisites: ['fractions.multiply-by-whole'],
  },
  {
    id: 'fractions.divide-unit-fraction',
    name: 'Divide with unit fractions',
    operation: 'fractions',
    grade: 5,
    standards: ['5.NF.B.7'],
    prerequisites: ['fractions.multiply-fractions'],
  },
  {
    id: 'fractions.divide-fractions',
    name: 'Divide fractions by fractions',
    operation: 'fractions',
    grade: 6,
    standards: ['6.NS.A.1'],
    prerequisites: ['fractions.divide-unit-fraction', 'fractions.multiply-fractions'],
  },
];
