import type { SkillDefinition } from '../types';

export const MULTIPLICATION_SKILLS: readonly SkillDefinition[] = [
  {
    id: 'multiplication.equal-groups',
    name: 'Equal groups concept',
    operation: 'multiplication',
    grade: 2,
    standards: ['2.OA.C.4'],
    prerequisites: [
      'addition.within-20.with-carry',
      'place-value.skip-counting',
    ],
  },
  {
    id: 'multiplication.arrays',
    name: 'Arrays (rows × columns)',
    operation: 'multiplication',
    grade: 2,
    standards: ['2.OA.C.4'],
    prerequisites: ['multiplication.equal-groups'],
  },
  {
    id: 'multiplication.repeated-addition',
    name: 'Repeated addition',
    operation: 'multiplication',
    grade: 2,
    standards: ['2.OA.C.4'],
    prerequisites: ['multiplication.equal-groups'],
  },
  {
    id: 'multiplication.facts-2-5-10',
    name: 'Times tables 2, 5, 10',
    operation: 'multiplication',
    grade: 3,
    standards: ['3.OA.C.7'],
    prerequisites: ['multiplication.arrays', 'multiplication.repeated-addition'],
  },
  {
    id: 'multiplication.facts-3-4-6',
    name: 'Times tables 3, 4, 6',
    operation: 'multiplication',
    grade: 3,
    standards: ['3.OA.C.7'],
    prerequisites: ['multiplication.facts-2-5-10'],
  },
  {
    id: 'multiplication.facts-7-8-9',
    name: 'Times tables 7, 8, 9',
    operation: 'multiplication',
    grade: 3,
    standards: ['3.OA.C.7'],
    prerequisites: ['multiplication.facts-3-4-6'],
  },
  {
    id: 'multiplication.by-10-100',
    name: 'Multiply by 10, 100',
    operation: 'multiplication',
    grade: 3,
    standards: ['3.NBT.A.3'],
    prerequisites: ['multiplication.facts-2-5-10'],
  },
  {
    id: 'multiplication.two-by-one',
    name: '2-digit × 1-digit',
    operation: 'multiplication',
    grade: 4,
    standards: ['4.NBT.B.5'],
    prerequisites: ['multiplication.facts-7-8-9', 'multiplication.by-10-100'],
  },
  {
    id: 'multiplication.two-by-two',
    name: '2-digit × 2-digit',
    operation: 'multiplication',
    grade: 4,
    standards: ['4.NBT.B.5'],
    prerequisites: ['multiplication.two-by-one'],
  },
  {
    id: 'multiplication.four-by-one',
    name: 'Up to 4-digit × 1-digit',
    operation: 'multiplication',
    grade: 4,
    standards: ['4.NBT.B.5'],
    prerequisites: ['multiplication.two-by-one'],
  },
];
