import type { SkillDefinition } from '../types';

export const PLACE_VALUE_SKILLS: readonly SkillDefinition[] = [
  {
    id: 'place-value.ones-tens',
    name: 'Tens and ones',
    operation: 'place_value',
    grade: 1,
    standards: ['1.NBT.B.2'],
    prerequisites: [],
  },
  {
    id: 'place-value.hundreds',
    name: 'Hundreds place',
    operation: 'place_value',
    grade: 2,
    standards: ['2.NBT.A.1'],
    prerequisites: ['place-value.ones-tens'],
  },
  {
    id: 'place-value.to-1000',
    name: 'Read/write numbers to 1000',
    operation: 'place_value',
    grade: 2,
    standards: ['2.NBT.A.3'],
    prerequisites: ['place-value.hundreds'],
  },
  {
    id: 'place-value.comparing',
    name: 'Compare numbers (<, >, =)',
    operation: 'place_value',
    grade: 2,
    standards: ['2.NBT.A.4'],
    prerequisites: ['place-value.hundreds'],
  },
  {
    id: 'place-value.skip-counting',
    name: 'Skip count (2s, 5s, 10s, 100s)',
    operation: 'place_value',
    grade: 2,
    standards: ['2.NBT.A.2'],
    prerequisites: ['place-value.ones-tens'],
  },
  {
    id: 'place-value.rounding-10-100',
    name: 'Round to nearest 10 or 100',
    operation: 'place_value',
    grade: 3,
    standards: ['3.NBT.A.1'],
    prerequisites: ['place-value.comparing'],
  },
  {
    id: 'place-value.to-10000',
    name: 'Place value to 10,000',
    operation: 'place_value',
    grade: 4,
    standards: ['4.NBT.A.2'],
    prerequisites: ['place-value.rounding-10-100'],
  },
  {
    id: 'place-value.expanded-form',
    name: 'Expanded form',
    operation: 'place_value',
    grade: 4,
    standards: ['4.NBT.A.2'],
    prerequisites: ['place-value.to-10000'],
  },
  {
    id: 'place-value.decimal-identify',
    name: 'Identify decimal digit',
    operation: 'place_value',
    grade: 5,
    standards: ['5.NBT.A.1'],
    prerequisites: ['place-value.expanded-form'],
  },
  {
    id: 'place-value.decimal-decompose',
    name: 'Decompose decimals',
    operation: 'place_value',
    grade: 5,
    standards: ['5.NBT.A.1'],
    prerequisites: ['place-value.decimal-identify'],
  },
  {
    id: 'place-value.decimal-compare',
    name: 'Compare decimals',
    operation: 'place_value',
    grade: 5,
    standards: ['5.NBT.A.3b'],
    prerequisites: ['place-value.decimal-identify'],
  },
  {
    id: 'place-value.decimal-rounding',
    name: 'Round decimals',
    operation: 'place_value',
    grade: 5,
    standards: ['5.NBT.A.4'],
    prerequisites: ['place-value.decimal-compare', 'place-value.rounding-10-100'],
  },
];
